project_name: pulsarctl

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.ReleaseVersion=v{{ .Version }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.BuildTS={{ .Date }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.GitHash={{ .FullCommit }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.GitBranch={{ .Branch }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.GoVersion={{ .Env.GO_VERSION }}

archives:
  - name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    files:
      - plugins/*

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github

brews:
  - name: pulsarctl@master
    tap:
      owner: streamnative
      name: homebrew-streamnative
    skip_upload: "true"
    folder: Formula
    homepage: "https://streamnative.io/"
    description: "A CLI for Apache Pulsar written in Go"
    license: "Apache-2.0"
    url_template: "https://github.com/streamnative/pulsarctl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script Dir["#{libexec}/pulsarctl"]
      bin.write_exec_script Dir["#{libexec}/plugins/pulsarctl-security_tool"]
      
      (prefix/"completions").mkdir
      
      system "#{libexec}/pulsarctl completion zsh > #{prefix}/completions/_pulsarctl"
      system "#{libexec}/pulsarctl completion bash > #{prefix}/completions/pulsarctl.bash"
      
      zsh_completion.install "#{prefix}/completions/_pulsarctl"
      bash_completion.install "#{prefix}/completions/pulsarctl.bash"
      
      rmdir prefix/"completions"
    test: |
      out = shell_output("#{bin}/pulsarctl 2>&1")
      assert_contains "CLI for Apache Pulsar", out
