project_name: pulsarctl

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.ReleaseVersion={{ .Version }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.BuildTS={{ .Date }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.GitHash={{ .FullCommit }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.GitBranch={{ .Branch }}
      - -X github.com/streamnative/pulsarctl/pkg/cmdutils.GoVersion={{ .Env.GO_VERSION }}

archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    files:
      - plugins/*
