name: Pulsarctl
on:
  pull_request:
    branches:
      - '*'
    path-ignores:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
jobs:
  function-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Function tests
        run: scripts/run-integration-tests.sh function
  sink-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sink tests
        run: scripts/run-integration-tests.sh sink
  source-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Source tests
        run: scripts/run-integration-tests.sh source
