name: Pulsarctl

on:
  pull_request:
    branches:
      - '*'
    path-ignores:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'

jobs:
  release-check:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: [ 1.13, 1.14, 1.15, 1.16, 1.17, 1.18 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: build
        run: |
          $Env:CGO_ENABLED=0
          $Env:GOOS='linux'
          $Env:GOARCH='amd64'
          go build -o pulsarctl-amd64-linux -ldflags "-X github.com/streamnative/pulsarctl/pkg/pulsar.ReleaseVersion=Pulsarctl-Go" .
          $Env:GOOS='darwin'
          go build -o pulsarctl-amd64-darwin -ldflags "-X github.com/streamnative/pulsarctl/pkg/pulsar.ReleaseVersion=Pulsarctl-Go" .
          $Env:GOOS='windows'
          go build -o  pulsarctl-amd64-windows.exe -ldflags "-X github.com/streamnative/pulsarctl/pkg/pulsar.ReleaseVersion=Pulsarctl-Go" .
          go build -o  pulsarctl-386-windows.exe -ldflags "-X github.com/streamnative/pulsarctl/pkg/pulsar.ReleaseVersion=Pulsarctl-Go" .

